### ISSUE TITLE
ECM.4 - Coffees page

### ISSUE THREAD

**Issue by AnnaRusu** [AnnaRusu/coffee-den#15]
### ToDo
@Stefanacef 

- [x] Create a .json with dummy data representing coffees
- [x] Create the design for items' cards
- [x] Create an items filter

**Comment by AnnaRusu** [comment]
- [x] Create a .json with dummy data representing coffees
- [x] Create the design for items' cards
- [x] Create an items filter
- [ ] Create view-item page
